### ISSUE TITLE
Баг с категориями игры

### ISSUE THREAD

**Issue by llxodz** [llxodz/SpyGameiOS#21]
Если выбрать "Все категории" и при этом поменять что-то в настройках игры, то после выхода в контроллера все свитчи "выключатся", кроме самого верхнего с категорией "Выбрать все"

[Видео](https://user-images.githubusercontent.com/67876650/230436025-7c5d2f9d-cf11-4525-a4d7-17c798fd7e5b.mp4)

**Comment by andrewfirsenko** [comment]
https://github.com/llxodz/SpyGameiOS/pull/22
